version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: matchday-postgres
    environment:
      POSTGRES_DB: matchday
      POSTGRES_USER: matchday_user
      POSTGRES_PASSWORD: matchday_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matchday_user -d matchday"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: matchday-adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula

volumes:
  postgres_data: